CONFIG_FLASH_SIZE=76
CONFIG_GPIO=y
CONFIG_LOG_MAX_LEVEL=2
CONFIG_LOG_PRINTK=y
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_SRAM_SIZE=32
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_I2C_NEORV32=y
CONFIG_I2C=y

# DAC Support
CONFIG_DAC=y
CONFIG_DAC_MCP4725=y

# Optional shell support (disable if ROM is tight)
CONFIG_SHELL=y
CONFIG_SHELL_MINIMAL=y
CONFIG_DEVICE_SHELL=y
CONFIG_I2C_SHELL=y